### PR TITLE
fix(installer): set `$HOME` if not defined

### LINKED ISSUE #10680: Installation script is creating "~" directory
### Describe the bug

I have tried to install the oh-my-zsh through the installation.sh and I noticed that it's creating a "~" directory wherever I start the script. I think that the intention is to create the .oh-my-zsh in my user home directory but this isn't what is happening.

Because of this it can not find the ~/.zshrc-omztemp and this broke the script giving this error:
`./install.sh: 324: cannot create ~/.zshrc-omztemp: Directory nonexistent`

### Steps to reproduce

Download the  [installation](https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh) script
and run it with `./install.sh`

### Expected behavior

The expected behavior it is to complete the installation

### Screenshots and recordings

_No response_

### OS / Linux distribution

Pop OS 20.04

### Zsh version

5.8

### Oh My Zsh version

master (0da33ca)

### Terminal emulator

GNOME Terminal

### If using WSL on Windows, which version of WSL

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mcornella**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Defines `$HOME` if the variable is unset, which ended up creating a directory named `~` instead of using the user's home directory. See https://github.com/ohmyzsh/ohmyzsh/issues/10680#issuecomment-1047148767 for explanation.
- Unrelated: add `--quiet` to `git init` call since new git versions have a big prompt about the default branch when called without parameters.

## Other comments:

Fixes #10680

### CODE REVIEW

**Review by carlosala — APPROVED** [review]
nice workaround Marc!

File: tools/install.sh [hunk 1]
```diff
@@ -42,13 +42,17 @@ set -e
 # $USER is defined by login(1) which is not always executed (e.g. containers)
 # POSIX: https://pubs.opengroup.org/onlinepubs/009695299/utilities/id.html
 USER=${USER:-$(id -u -n)}
+# $HOME is defined at the time of login, but it could be unset. If it is unset,
+# a tilde by itself (~) will not be expanded to the current user's home directory.
+# POSIX: https://pubs.opengroup.org/onlinepubs/009696899/basedefs/xbd_chap08.html#tag_08_03
+HOME="${HOME:-$(getent passwd $USER | cut -d: -f6)}"
```
Comment (leftbin-swarup) [inline tools/install.sh:48]: this line is failing on mac as getent command is not found.

Comment (leftbin-swarup) [reply tools/install.sh:48]: ok i see, this only looks for getent if HOME is not defined.

Comment (mcornella) [reply tools/install.sh:48]: Fixed in 4f0b680248e1acf71e9e557af62f3a08bb5b96c6.
